# Generated by Django 3.2.5 on 2021-07-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='on_free_trial',
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.CharField(choices=[('INPUT', 'IN'), ('ANALYSIS', 'AN')], default='INPUT', max_length=10),
        ),
    ]
